<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="uye.aspx.cs" Inherits="uye" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1> ÜYELER </h1>
    <p> &nbsp;</p>

    <p> 
        
    </p>

    <%-- ÜYE EKLEME PANELİM --%>
        <asp:Panel ID="Panel1" runat="server">
        <p> &nbsp;</p>

        <div class="kitapeklebaslik">
            <h5>ÜYE EKLE </h5>
        </div>
        <table class="kitapekle"  >

        <tr> 
            <td class="auto-style1" > TC:</td>
            <td class="auto-style1"> <asp:TextBox ID="TextBox1" runat="server"  Cssclass="TextBox2 TextBox"></asp:TextBox></td>

        </tr>
        <tr> 
            <td> AD:</td>
            <td> <asp:TextBox ID="TextBox2" runat="server"  Cssclass="TextBox2 TextBox" ></asp:TextBox></td>
        </tr>
        <tr> 
            <td> SOYAD:</td>
            <td> <asp:TextBox ID="TextBox3" runat="server"  Cssclass="TextBox2 TextBox"></asp:TextBox></td>
        </tr>
        <tr> 
            <td> TEL:</td>
            <td> <asp:TextBox ID="TextBox9" runat="server"  Cssclass="TextBox2 TextBox"></asp:TextBox></td>
        </tr>
        <tr> 
            <td> MAİL:</td>
            <td> <asp:TextBox ID="TextBox4" runat="server"  Cssclass="TextBox2 TextBox"></asp:TextBox></td>
        </tr>
        <tr> 
            <td> ŞİFRE:</td>
            <td> <asp:TextBox ID="TextBox5" runat="server"  Cssclass="TextBox2 TextBox"></asp:TextBox></td>
        </tr>
        <tr> 
            <td> YETKİ:</td>
            <td><asp:DropDownList ID="DropDownList1" runat="server" CssClass="TextBox2 TextBox" Width="150">
                <asp:ListItem Value="normal_uye">normal üye</asp:ListItem>
                <asp:ListItem>admin</asp:ListItem>
            </asp:DropDownList> </td>
            
        </tr>

        <tr> 
            <td colspan ="2">    
                <br />
                <asp:Button ID="Button1" runat="server" Text="TEMİZLE" Cssclass="button1" OnClick="Button1_Click" />
                &nbsp;
                <asp:Button ID="Button2" runat="server" Text="KAYDET" OnClick="Button2_Click" Cssclass="button1"/>
                <br />
                <asp:LinkButton ID="lblDurum" runat="server" CssClass="imjusttext" OnClick="LinkButton1_Click" ForeColor="Red" Visible="False">LinkButton </asp:LinkButton>
            </td>
        </tr>


    </table>

    </asp:Panel>


    <br />



        <div class="uyeGridView">
            <%-- ÜYE DÜZENLEME/SİLME İŞLEMLERİNİ GERÇEKLEŞTİRDİĞİM GRIDVIEW --%>
            <%-- GRIDVIEW SİL/DÜZENLE BUTONLARIMI BU KODLARLA AKTİFLEŞTİRİYORUM: AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" --%>
            <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="tc" DataSourceID="SqlDataSource1" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" CssClass="GridMain">
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <Columns>
                    <%-- SÜTUNLARIMIN EKLİYORUM. TC BİRİNCİL ANAHTAR OLDUĞU İÇİN DEĞİŞTİRİLMESİNİ İSTEMİYORUM --%>
                    <asp:BoundField DataField="tc" HeaderText="tc" ReadOnly="true" SortExpression="tc" />
                    <asp:BoundField DataField="ad" HeaderText="ad" SortExpression="ad" />
                    <asp:BoundField DataField="soyad" HeaderText="soyad" SortExpression="soyad" />
                    <asp:BoundField DataField="tel" HeaderText="tel" SortExpression="tel" />
                    <asp:BoundField DataField="mail" HeaderText="mail" SortExpression="mail" />
                    <asp:BoundField DataField="sifre" HeaderText="sifre" SortExpression="sifre" />
                    <asp:BoundField DataField="yetki" HeaderText="yetki" SortExpression="yetki" />
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <%-- VERİ KAYNAĞIMI BELİRTİYORUM. --%>
            <%-- SelectCommand, UpdateCommand, DeleteCommand Komutlarıyla tek satırda Listeleme/güncelleme/silme işlemlerini hallediyorum (Yardım aldığım video: https://www.youtube.com/watch?v=xybe0fpj_10)  --%>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:kutuphaneConnectionString %>" SelectCommand="SELECT * FROM [uyeler]" UpdateCommand="UPDATE [uyeler] set [ad]=@ad, [soyad]=@soyad, [tel]=@tel, [mail]=@mail, [sifre]=@sifre, [yetki]=@yetki where [tc] =@tc" DeleteCommand="Delete from [uyeler] where [tc]=@tc"></asp:SqlDataSource>
        </div>
    <br />
    <br />
    <br />

</asp:Content>